"use client";
import { useEffect, useMemo, useState } from "react";

type Product={id:number;name:string;category:string;description:string;price:number;compareAtPrice:number|null;image:string;tag:string;stock:number;published:boolean;featured:boolean};
const categories = [
  { name: "Jewellery", note: "Everyday glow", image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=85" },
  { name: "Beauty", note: "Rituals, refined", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=85" },
  { name: "Accessories", note: "The finishing touch", image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=900&q=85" },
];

export default function Home() {
  const [menu, setMenu] = useState(false), [search, setSearch] = useState(false);
  const [products,setProducts]=useState<Product[]>([]),[query, setQuery] = useState(""), [cart, setCart] = useState<Product[]>([]);
  const [cartOpen, setCartOpen] = useState(false), [checkout, setCheckout] = useState(false);
  const [wishlistOpen,setWishlistOpen]=useState(false);
  const [customer, setCustomer] = useState({name:"", phone:"", address:"", pincode:""});
  const [saved, setSaved] = useState<string[]>(()=>{if(typeof window==="undefined")return [];try{return JSON.parse(localStorage.getItem("zavelia-wishlist")||"[]")}catch{return []}}), [notice, setNotice] = useState("");
  useEffect(()=>{fetch("/api/products").then(r=>r.json()).then(d=>setProducts(d.products||[]))},[]);
  const results = useMemo(() => products.filter(p => `${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())), [query,products]);
  const toggleSaved=(id:number)=>setSaved(s=>{const next=s.includes(String(id))?s.filter(x=>x!==String(id)):[...s,String(id)];localStorage.setItem("zavelia-wishlist",JSON.stringify(next));return next});
  const add = (name: string) => { const item=products.find(p=>p.name===name); if(item) setCart(v=>[...v,item]); setNotice(`${name} added to your bag`); setTimeout(() => setNotice(""), 2200); };
  const subtotal=cart.reduce((sum,p)=>sum+p.price,0), shipping=subtotal>=999?0:49;
  const placeOrder=(e:React.FormEvent)=>{e.preventDefault();const ref=`ZAV-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const items=cart.map((p,i)=>`${i+1}. ${p.name} — ₹${p.price.toLocaleString('en-IN')}`).join('\n');const message=`Hello ZAVÉLIA, I would like to place an order.\n\nOrder reference: ${ref}\n${items}\n\nSubtotal: ₹${subtotal.toLocaleString('en-IN')}\nShipping: ${shipping?`₹${shipping}`:'Free'}\nTotal: ₹${(subtotal+shipping).toLocaleString('en-IN')}\n\nCustomer: ${customer.name}\nPhone: ${customer.phone}\nDelivery address: ${customer.address}, PIN ${customer.pincode}\n\nPlease confirm availability and payment details.`;window.open(`https://wa.me/919063266307?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');setNotice(`Order ${ref} prepared in WhatsApp`);};
  return <main>
    <a className="skip" href="#content">Skip to content</a>
    <div className="announcement">COMPLIMENTARY SHIPPING ABOVE ₹999 <span>•</span> EASY 7-DAY RETURNS</div>
    <header className="header"><button className="icon mobile" aria-label="Open menu" onClick={() => setMenu(true)}>☰</button><a className="logo" href="#">ZAVÉLIA<span>adorn your every mood</span></a><nav aria-label="Main navigation">{['New In','Jewellery','Beauty','Accessories','Gifting'].map(x => <a href="#new-in" key={x}>{x}</a>)}<a className="sale" href="#edit">The Edit</a></nav><div className="actions"><button className="icon" aria-label="Search" onClick={() => setSearch(true)}>⌕</button><button className="icon" aria-label={`Wishlist with ${saved.length} items`} onClick={()=>setWishlistOpen(true)}>♡</button><button className="bag" onClick={()=>setCartOpen(true)} aria-label={`Shopping bag with ${cart.length} items`}>BAG <b>{cart.length}</b></button></div></header>
    {menu && <div className="overlay" role="dialog" aria-modal="true" aria-label="Navigation menu"><button className="close" onClick={() => setMenu(false)} aria-label="Close menu">×</button><p className="eyebrow">EXPLORE ZAVÉLIA</p>{['New In','Jewellery','Beauty','Accessories','Hair Accessories','Bags & Wallets','Gifting','Offers'].map(x => <a href="#content" onClick={() => setMenu(false)} key={x}>{x}<span>→</span></a>)}</div>}
    {search && <div className="search-panel" role="dialog" aria-modal="true" aria-label="Search products"><div><label htmlFor="search">What are you looking for?</label><input autoFocus id="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Try ‘gold hoops’ or ‘serum’"/><button onClick={() => setSearch(false)} aria-label="Close search">×</button></div><p className="eyebrow">{query ? `${results.length} RESULTS` : 'POPULAR NOW'}</p>{(query ? results : products.slice(0,3)).map(p => <button className="search-result" key={p.name} onClick={() => {setSearch(false); document.getElementById('new-in')?.scrollIntoView()}}><img src={p.image} alt=""/><span>{p.name}<small>{p.category} · ₹{p.price.toLocaleString('en-IN')}</small></span><b>→</b></button>)}</div>}
    {wishlistOpen&&<div className="drawer-backdrop" onClick={()=>setWishlistOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-label="Wishlist" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setWishlistOpen(false)} aria-label="Close wishlist">×</button><p className="eyebrow">YOUR WISHLIST · {saved.length}</p><h2>Saved for later.</h2>{saved.length===0?<div className="empty-cart"><p>Tap the heart on any product to save it here.</p><button onClick={()=>setWishlistOpen(false)}>DISCOVER PRODUCTS</button></div>:<div className="cart-lines">{products.filter(p=>saved.includes(String(p.id))).map(p=><article key={p.id}><img src={p.image} alt=""/><div><h3>{p.name}</h3><small>{p.category}</small><b>₹{p.price.toLocaleString('en-IN')}</b><button className="wishlist-add" onClick={()=>add(p.name)}>ADD TO BAG</button></div><button aria-label={`Remove ${p.name} from wishlist`} onClick={()=>toggleSaved(p.id)}>×</button></article>)}</div>}</aside></div>}
    {cartOpen && <div className="drawer-backdrop" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-label="Shopping bag" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setCartOpen(false)} aria-label="Close shopping bag">×</button><p className="eyebrow">YOUR BAG · {cart.length} {cart.length===1?'ITEM':'ITEMS'}</p><h2>Ready when you are.</h2>{cart.length===0?<div className="empty-cart"><p>Your bag is waiting for something beautiful.</p><button onClick={()=>setCartOpen(false)}>CONTINUE SHOPPING</button></div>:<><div className="cart-lines">{cart.map((p,i)=><article key={`${p.name}-${i}`}><img src={p.image} alt=""/><div><h3>{p.name}</h3><small>{p.category}</small><b>₹{p.price.toLocaleString('en-IN')}</b></div><button aria-label={`Remove ${p.name}`} onClick={()=>setCart(c=>c.filter((_,x)=>x!==i))}>×</button></article>)}</div><div className="totals"><span>Subtotal <b>₹{subtotal.toLocaleString('en-IN')}</b></span><span>Shipping <b>{shipping?`₹${shipping}`:'Complimentary'}</b></span><strong>Total <b>₹{(subtotal+shipping).toLocaleString('en-IN')}</b></strong></div><button className="checkout-btn" onClick={()=>{setCartOpen(false);setCheckout(true)}}>CONTINUE TO WHATSAPP ORDER →</button><small className="safe-note">No payment is taken now. Your order is confirmed only after ZAVÉLIA replies on WhatsApp.</small></>}</aside></div>}
    {checkout && <div className="checkout-modal" role="dialog" aria-modal="true" aria-label="Delivery details"><form onSubmit={placeOrder}><button type="button" className="drawer-close" onClick={()=>setCheckout(false)} aria-label="Close checkout">×</button><p className="eyebrow">SECURE ORDER REQUEST</p><h2>Where should we deliver?</h2><p>Enter your delivery details. We’ll open WhatsApp with your order summary for confirmation.</p><label>Full name<input required minLength={2} value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} placeholder="Your full name"/></label><label>Mobile number<input required inputMode="numeric" pattern="[6-9][0-9]{9}" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value.replace(/\D/g,'').slice(0,10)})} placeholder="10-digit Indian mobile number"/></label><label>Complete delivery address<textarea required minLength={10} value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})} placeholder="House, street, area, city and state"/></label><label>PIN code<input required inputMode="numeric" pattern="[0-9]{6}" value={customer.pincode} onChange={e=>setCustomer({...customer,pincode:e.target.value.replace(/\D/g,'').slice(0,6)})} placeholder="6-digit PIN code"/></label><label className="consent"><input type="checkbox" required/> I agree to share these details with ZAVÉLIA through WhatsApp to process this order.</label><div className="order-total">Order total <b>₹{(subtotal+shipping).toLocaleString('en-IN')}</b></div><button className="checkout-btn" type="submit">OPEN WHATSAPP TO PLACE ORDER →</button><small className="safe-note">WhatsApp will open to +91 90632 66307. Opening WhatsApp does not reserve stock or confirm your order.</small></form></div>}
    <section className="hero" id="content"><img src="https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1800&q=90" alt="Gold jewellery styled on warm sculptural fabric"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">THE FESTIVE EDIT · 2026</p><h1>Your mood.<br/><em>Your moment.</em></h1><p>Jewellery, beauty and accessories curated for every version of you.</p><a className="button light" href="#new-in">SHOP THE EDIT <span>→</span></a></div><div className="hero-index"><span>01</span><i/><span>04</span></div></section>
    <section className="intro"><p className="eyebrow">A WORLD OF SELF-EXPRESSION</p><h2>Not just what you wear.<br/><em>How you feel wearing it.</em></h2><p className="intro-copy">ZAVÉLIA brings together thoughtful details, expressive colour and modern rituals—chosen to make getting ready the best part of your day.</p></section>
    <section className="categories" aria-label="Shop categories">{categories.map((c,i) => <a href="#new-in" className={`category c${i}`} key={c.name}><img src={c.image} alt={`${c.name} collection`}/><div><span>{c.note}</span><h3>{c.name}</h3><b>EXPLORE →</b></div></a>)}</section>
    <section className="new" id="new-in"><div className="section-head"><div><p className="eyebrow">FRESHLY CURATED</p><h2>Accessories & beauty</h2></div><span>{products.length} PRODUCTS</span></div><div className="product-grid">{products.map(p => <article className="product" key={p.id}><div className="product-image"><img src={p.image} alt={p.name}/><span>{p.stock>0?p.tag:"SOLD OUT"}</span><button className={saved.includes(String(p.id)) ? 'active' : ''} onClick={() => toggleSaved(p.id)} aria-label={`Save ${p.name}`}>♡</button><button className="quick" disabled={p.stock<1} onClick={() => add(p.name)}>{p.stock<1?"SOLD OUT":"QUICK ADD"}</button></div><p>{p.category}</p><h3>{p.name}</h3><div className="price">₹{p.price.toLocaleString('en-IN')} {p.compareAtPrice&&p.compareAtPrice>p.price?<del>₹{p.compareAtPrice.toLocaleString('en-IN')}</del>:null}</div></article>)}</div></section>
    <section className="story" id="edit"><div className="story-copy"><p className="eyebrow">THE ZAVÉLIA EDIT</p><h2>Details make<br/>the <em>difference.</em></h2><p>Small rituals. Bold choices. Pieces that move from coffee runs to celebrations—and still feel unmistakably yours.</p><a href="#new-in" className="button dark">DISCOVER OUR STORY <span>→</span></a></div><div className="story-image"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1400&q=85" alt="Woman styling a contemporary fashion look"/><div className="stamp">Z<br/><span>CURATED WITH INTENT</span></div></div></section>
    <section className="promise"><p className="eyebrow">WHY ZAVÉLIA</p><div><article><b>01</b><h3>Curated, not crowded</h3><p>Thoughtful edits designed to make choosing feel effortless.</p></article><article><b>02</b><h3>Details you can trust</h3><p>Clear materials, care guidance and honest product information.</p></article><article><b>03</b><h3>Support that feels human</h3><p>Helpful assistance before, during and after your order.</p></article></div></section>
    <section className="newsletter"><p className="eyebrow">NOTES FROM ZAVÉLIA</p><h2>A little beauty in your inbox.</h2><p>New edits, styling stories and private previews—never noise.</p><form onSubmit={e => {e.preventDefault(); setNotice('You’re on the list — welcome to ZAVÉLIA.')}}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" required placeholder="Your email address"/><button>JOIN THE LIST →</button></form><small>By subscribing, you agree to receive ZAVÉLIA updates. Unsubscribe anytime.</small></section>
    <footer><div className="footer-brand"><a className="logo" href="#">ZAVÉLIA<span>adorn your every mood</span></a><p>A curated destination for jewellery, beauty and accessories that celebrate every version of you.</p></div><div><h3>SHOP</h3><a href="#new-in">New In</a><a href="#new-in">Jewellery</a><a href="#new-in">Beauty</a><a href="#new-in">Accessories</a><a href="#new-in">Gifting</a></div><div><h3>HELP</h3><a href="mailto:adityavardhan394@gmail.com">Contact us</a><a href="#">Shipping</a><a href="#">Returns</a><a href="https://wa.me/919063266307" target="_blank" rel="noreferrer">Order support</a><a href="#">FAQs</a></div><div><h3>ABOUT</h3><a href="#edit">Our story</a><a href="#">Care guide</a><a href="#">Privacy</a><a href="#">Terms</a></div><div className="footer-note"><h3>WE’RE HERE TO HELP</h3><a href="https://wa.me/919063266307" target="_blank" rel="noreferrer">WhatsApp: +91 90632 66307</a><a href="mailto:adityavardhan394@gmail.com">adityavardhan394@gmail.com</a><p>Orders are confirmed through WhatsApp after availability review.</p></div></footer>
    <div className="copyright">© 2026 ZAVÉLIA. ALL RIGHTS RESERVED. <span>MADE WITH INTENTION.</span></div>{notice && <div className="toast" role="status">✓ {notice}</div>}
  </main>;
}
